Name:		texlive-minim-xmp
Version:	69352
Release:	1
Summary:	Embed XMP metadata in PDF with LuaTeX
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/macros/latex/contrib/minim-xmp
License:	other-free
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/minim-xmp.r%{version}.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/minim-xmp.doc.r%{version}.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Requires(post):	texlive-kpathsea

%description
This package enables the inclusion of XMP (eXtensible Metadata
Platform) data in the pdf output generated by (plain) LuaTeX.
The use of XMP is required by PDF standards such as PDF/A.

%prep
%autosetup -p1 -c -a1

%build

%install
rm -rf tlpkg
mkdir -p %{buildroot}%{_texmfdistdir}
cp -a * %{buildroot}%{_texmfdistdir}

%files
%{_texmfdistdir}/tex/luatex/minim-xmp
%doc %{_texmfdistdir}/doc/luatex/minim-xmp

%post -p %{_sbindir}/texlive.post

%postun
[ "$1" -eq 0 ] && %{_sbindir}/texlive.post
